name: Test Build

on: [workflow_dispatch]

jobs:

  build_wheel:
    name: Build wheel
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install "setuptools>=67.8.0"
        pip install wheel build PyYAML
    - name: Build .whl
      run: python -m build --wheel --skip-dependency-check
    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: pypi-wheel
        path: dist/*.whl

  build_source:
    name: Build source
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install "setuptools>=67.8.0"
        pip install wheel build PyYAML
    - name: Build .tar.gz
      run: python -m build --sdist --skip-dependency-check
    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: pypi-source-dist
        path: dist/*.tar.gz

  test_pkg_dist:
    name: Test distribution
    needs: [build_wheel, build_source]
    runs-on: macos-13
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Collect and extract artifact
      uses: actions/download-artifact@v4
      with:
        path: dist
        pattern: pypi-*
        merge-multiple: true
    - name: Test .whl
      run: |
        cd dist
        python -m pip install --upgrade pip
        pip install *.whl
        pip show pyppbox
    - name: Uninstall pyppbox
      run: pip uninstall -y pyppbox
    - name: Test .tar.gz
      run: |
        cd dist
        python -m pip install --upgrade pip
        pip install *.tar.gz
        pip show pyppbox
